### ISSUE TITLE
Add routing

### ISSUE THREAD

**Issue by thatoddmailbox** [daltonschool/Foody#1]
https://alexgaribay.com/2015/07/05/getting-started-with-meteor-react-and-react-router/

**Comment by cforster** [comment]
List (includes search, favorites)
Write recipe
run recipe

**Comment by jstettner** [comment]
Just did this in commit 10fb5dccb488df94798727d259debe308c016bf6

**Comment by jstettner** [comment]
BTW. currently routes every address to feed but I will create new views soon.
